<a href="https://colab.research.google.com/github/AndriiVasylenkoML/probability-theory-and-statistics/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лінійна регресія. Знаходження параметрів вибіркового рівняння прямої лінії регресії. Лінійний коефіцієнт кореляції.


Рівняння регресії подається у вигляді у = аx + b

Знайти рівняння лінійної регресії y на х,  
[![image.png](https://i.postimg.cc/KzZNNDS7/image.png)](https://postimg.cc/rdPxyWpz)

Дані спосaережень для випадкових величин X і Y наведені в кореляційній таблиці:   
[![image.png](https://i.postimg.cc/FzccjYC5/image.png)](https://postimg.cc/0Kkbvyqc)

In [ ]:
import numpy as np

# Дані спостережень (кореляційна таблиця)
X_values = np.array([15, 20, 25, 30, 35, 40])
Y_values = np.array([5, 10, 15, 20, 25])

# Частоти nx (по X) і ny (по Y)
nx = np.array([4, 8, 12, 57, 15, 4])
ny = np.array([6, 10, 53, 16, 15])

# Загальна кількість спостережень
n_total = 100

# Частоти для кожної пари (X, Y)
frequencies = np.array([
    [4, 2, 0, 0, 0, 0],  # Y = 5
    [0, 6, 4, 0, 0, 0],  # Y = 10
    [0, 0, 6, 45, 2, 0],  # Y = 15
    [0, 0, 2, 8, 6, 0],  # Y = 20
    [0, 0, 0, 4, 7, 4]   # Y = 25
])

In [ ]:
mean_x = np.sum(X_values * nx) / np.sum(nx)
mean_y = np.sum(Y_values * ny) / np.sum(ny)

print(f"""
Знаходимо середні значення X і Y (зважені середні):
\nmean_x = np.sum({X_values} * {nx}) / np.sum({nx})
\nmean_x = np.sum({X_values * nx}) / {np.sum(nx)}
\nmean_x = {np.sum(X_values * nx)} / {np.sum(nx)}
\nmean_x = {mean_x}
\nmean_y = np.sum({Y_values} * {ny}) / np.sum({ny})
\nmean_y = np.sum({Y_values * ny}) / {np.sum(ny)}
\nmean_y = {np.sum(Y_values * ny)} / {np.sum(ny)}
\nmean_y = {mean_y}
""")


Знаходимо середні значення X і Y (зважені середні):

mean_x = np.sum([15 20 25 30 35 40] * [ 4  8 12 57 15  4]) / np.sum([ 4  8 12 57 15  4])

mean_x = np.sum([  60  160  300 1710  525  160]) / 100

mean_x = 2915 / 100

mean_x = 29.15

mean_y = np.sum([ 5 10 15 20 25] * [ 6 10 53 16 15]) / np.sum([ 6 10 53 16 15])

mean_y = np.sum([ 30 100 795 320 375]) / 100

mean_y = 1620 / 100

mean_y = 16.2



In [ ]:
Sxy = np.sum(frequencies * np.outer(Y_values - mean_y, X_values - mean_x))
Sxx = np.sum(frequencies * (X_values - mean_x)**2)
Syy = np.sum(frequencies.T * (Y_values - mean_y)**2)

print(f"""
Підготовка до знаходження параметрів регресії.
\nЗнаходимо суми для розрахунку коефіцієнтів:
\nSxy = np.sum(\n{frequencies} * np.outer({Y_values} - {mean_y}, {X_values} - {mean_x}))
\nSxy = np.sum(\n{frequencies} * {np.outer(Y_values - mean_y, X_values - mean_x)})
\nSxy = np.sum(\n{frequencies * np.outer(Y_values - mean_y, X_values - mean_x)})
\nSxy = {Sxy}
\nSxx = np.sum(\n{frequencies} * ({X_values} - {mean_x})**2)
\nSxx = np.sum(\n{frequencies} * {(X_values - mean_x)**2})
\nSxx = np.sum(\n{frequencies * (X_values - mean_x)**2})
\nSxx = {Sxx}
\nSyy = np.sum(\n{frequencies.T} * ({Y_values} - {mean_y})**2)
\nSyy = np.sum(\n{frequencies.T} * {(Y_values - mean_y)**2})
\nSyy = np.sum(\n{frequencies.T * (Y_values - mean_y)**2}
""")



Підготовка до знаходження параметрів регресії.

Знаходимо суми для розрахунку коефіцієнтів:

Sxy = np.sum(
[[ 4  2  0  0  0  0]
 [ 0  6  4  0  0  0]
 [ 0  0  6 45  2  0]
 [ 0  0  2  8  6  0]
 [ 0  0  0  4  7  4]] * np.outer([ 5 10 15 20 25] - 16.2, [15 20 25 30 35 40] - 29.15))

Sxy = np.sum(
[[ 4  2  0  0  0  0]
 [ 0  6  4  0  0  0]
 [ 0  0  6 45  2  0]
 [ 0  0  2  8  6  0]
 [ 0  0  0  4  7  4]] * [[ 158.48  102.48   46.48   -9.52  -65.52 -121.52]
 [  87.73   56.73   25.73   -5.27  -36.27  -67.27]
 [  16.98   10.98    4.98   -1.02   -7.02  -13.02]
 [ -53.77  -34.77  -15.77    3.23   22.23   41.23]
 [-124.52  -80.52  -36.52    7.48   51.48   95.48]])

Sxy = np.sum(
[[633.92 204.96   0.    -0.    -0.    -0.  ]
 [  0.   340.38 102.92  -0.    -0.    -0.  ]
 [  0.     0.    29.88 -45.9  -14.04  -0.  ]
 [ -0.    -0.   -31.54  25.84 133.38   0.  ]
 [ -0.    -0.    -0.    29.92 360.36 381.92]])

Sxy = 2152.0

Sxx = np.sum(
[[ 4  2  0  0  0  0]
 [ 0  6  4  0  0  0]
 [ 0  0  6 45  2  0]
 [ 0  

In [ ]:
r_b = Sxy / np.sqrt(Sxx * Syy)

print(f"""
Лінійний коефіцієнт кореляції:
r_b = {Sxy} / np.sqrt({Sxx} * {Syy})
r_b = {Sxy / np.sqrt(Sxx * Syy)}
""")


Лінійний коефіцієнт кореляції:
r_b = 2152.0 / np.sqrt(2702.75 * 2606.0)
r_b = 0.8108716622846192



In [ ]:
b = r_b * (np.sqrt(Syy) / np.sqrt(Sxx))
a = mean_y - b * mean_x

print(f"""
Параметри рівняння регресії:
\nb = {r_b} * (np.sqrt({Syy}) / np.sqrt({Sxx}))
\na = {mean_y} - {b} * {mean_x}
\nВідповідь:
\na = {a}
\nb = {b}
""")


Параметри рівняння регресії:

b = 0.8108716622846192 * (np.sqrt(2606.0) / np.sqrt(2702.75))

a = 16.2 - 0.7962260660438443 * 29.15

Відповідь:

a = -7.00998982517806

b = 0.7962260660438443

